# Generated by Django 2.1.1 on 2019-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190702_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(max_length=10000),
        ),
    ]
