# Generated by Django 2.1.1 on 2019-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190702_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
