# Generated by Django 2.1.1 on 2019-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190702_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='average_list',
            field=models.CharField(default=[], max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='average_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
